### ISSUE TITLE
Issue on Icons

### ISSUE THREAD

**Issue by BantuNavya** [gak112/ArhaAppsAdminTesting#104]
Action :-  In these side Icons not accurate to texts
Acutal Output :- Like categories Icons symbol Question Mark '?' (this symbol is history ) and also offers icons symbol rupee (symbol)
Expected Output :-  Icons symbols and text should but accurate  
![Screenshot 2024-05-23 185309](https://github.com/gak112/ArhaAppsAdminTesting/assets/170604838/f2e5efad-3b31-410a-aa7e-a95bebb97eb5)
![Screenshot 2024-05-23 185330](https://github.com/gak112/ArhaAppsAdminTesting/assets/170604838/c9dbfaab-2776-4b58-8dbf-3d82177fd0a6)

**Comment by QSPaysys1** [comment]
@srinivasmudhiraj3 Please check this icons and send to srinu anna and he will update

**Comment by srinivasmudhiraj3** [comment]
Job done
