### ISSUE TITLE
Design issue in white board 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#107]
Result :- The delete option were not aligned properly in the given field 
Actual Result:- when I selected multiple currency details when I inspected it shows following output 
Expected result :- The media query of delete is should be with in the field 
![money](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/3acd80ff-edf4-4f1c-91dc-9efb80e49392)

**Comment by qspaysys2** [comment]
Issue resolved
