### ISSUE TITLE
Issue in white board >> Design issue 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#150]
Description :- Mobile view of personal Information 
Expected result :- The designed component should be with in the field 
Actual Result :- The design is coming outside the field 
![a](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/f86eaa3f-6a36-4349-abc8-1b99179b4f47)

**Comment by qspaysys2** [comment]
issue resolved
