### ISSUE TITLE
StoreX:: Issues:: Testing:>> Company Name:: >>Store Details::

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#151]
Result:- There is a small suggestion about the Company name in Store Details of StoreX

Actual Output:- It was showing "Please enter valid company name" when I tried to enter some Special Characters in the Company name 

Expected Output:- Some Company names will have Special Characters, It should allow special characters

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/cd1cee59-c394-4ed6-a97a-5d3427f11077)

**Comment by QSPaysys1** [comment]
issue resolved
