### ISSUE TITLE
Storex:: Redesign

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#165]
there was no spacing that 2 labels
![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/ebdb9930-9f48-4223-91a3-3b8c434c1bbe)

**Comment by svnashok** [comment]
Above Issued Resolved

**Comment by qspaysys2** [comment]
issue resolved

**Comment by svnashok** [comment]
Above Issued Resolved
