### ISSUE TITLE
Issue::>> StoreX::>> Bank Details::>> Testing::

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#180]
Result:- There is an issue in the bank details

Actual Output:- When I tried to submit the bank details without entering the bank name I got a popup Warning that tells to Enter a valid bank name even though I didn't Enter any bank name in the Input

Expected Input:- It should say "Please Enter Bank Name" if the user didn't enter his bank name and if the user enters their bank name or bank number wrong it should say "Please Enter Valid Details"

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/9b1d08fa-4be8-4f8e-894a-237a1ecc6a14)

**Comment by sankarnagarapu** [comment]
Issue Resolved @Snehanama19
