### ISSUE TITLE
White Board :- Home page >>

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#204]
Issue :- When we click the on the download the app store and get it from from google play it is not re directing to the page 

Actual Output :- in home page the when we click on the app store and google play it is not redirecting to the page 

Expected Output :- When we click on the app store and google store it should be direct to the particular site of the page 

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/68c3c98a-e0f9-43e9-84a9-3e2f3ed77fd3

**Comment by QSPaysys1** [comment]
we changed this design completely
