### ISSUE TITLE
Issue::>>StoreX>> Testing::>> Company Name Issue>> StoreX::>>

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#208]
Result:- There is an issue with the Company name in the StoreX

Actual Output:- When I entered Special Characters in the Company name it showed an Error and warned me to enter a valid company name but it also accepted the invalid company name and created a store on that name

Expected Output:- It should not allow the invalid name to add to the Store Name even after showing the error in the Company Name

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/d8d32918-95b5-4732-a37a-e0f9cc630670)

**Comment by QSPaysys1** [comment]
issue resolved
