### ISSUE TITLE
White Board :- Home page >>

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#210]
Issue :- When we click the on the contact us it is not re directing to the page

  Actual Output :- in home page the when we click on the contact us  it is not redirecting to the page and there is no action taking place 

  Expected Output :- When we click on the contact us  it should be direct to our website page or it should take any action 

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/b73efb45-6848-40b4-8992-1348f3ee37f2

**Comment by QSPaysys1** [comment]
we changed this design completly
