### ISSUE TITLE
Storex>>pending actions>>Services

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#221]
Categories:: the design will over flow not visibl eproperly please redesign the categories 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/69bb93f2-5c47-4399-b77b-f2b52e5632d2)

**Comment by qspaysys2** [comment]
Issue resolved

**Comment by svnashok** [comment]
Above Issued Resolved
