### ISSUE TITLE
White Board :- Homepage >> Mobile View 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#234]
Issue :- Home page of mobile view is not correctly given 

Actual Output :- when we are seeing in mobile view of iPhone SE there are some text which are came out of the input box 

Expected Output :- when we are about see in mobile view it should be  view  correctly without any extra texts 

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/fe48e05c-5cc9-4242-bca8-e8229292477d

**Comment by qspaysys2** [comment]
Issue resolved
