### ISSUE TITLE
<<Issue:: StoreX:: Profile Pending::Issue:: Testing::>>

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#240]
Result:- There is a small Suggestion on the Home page of StoreX Admin page

Actual Output:- There is a button that tells complete your profile and Pending on the home page of StoreX Admin, It shouldn't be like that because the Pending button is not for Profile but is to be Verified by the Admin of StoreX so, it should be in other text instead of Complete your profile

Expected Output:- It also can be like "Your Profile needs to be Verified" and then "Pending"

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/6c38889a-cb57-4028-9a09-1b7895f8f63a)

**Comment by QSPaysys1** [comment]
Above Design Changed
