### ISSUE TITLE
White Board :- Home page >> Mobile view >> iPhone XR

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#244]
Issue :- Home page of mobile view is not correctly given 

Actual Output :- when we are seeing in mobile view of iPhone XR  there are some text which are came out of the input box 

Expected Output :- when we are about see in mobile view it should be  view  correctly without any extra texts or input boxes
https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/e72dd554-4e07-4b42-b644-05b9de4a2bde

**Comment by qspaysys2** [comment]
Issue resolved
