### ISSUE TITLE
Issue in white board :: bank account

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#245]
Issue :- In Bank Account in account number taking multiple Numbers also in bank name taking multiple characters 
Expected Result :- In Account Number should take only 16 numbers and also in bank name mention specified characters 
Actual Result :- In Account number Taking Multiple Characters and bank name taking multiple characters

**Comment by sankarnagarapu** [comment]
Issue Resolved @sindhumodugu  bank no 16 limited and banks have dropdown
