### ISSUE TITLE
White Board :-  Homepage :; Mobile view >>iPhone 12 pro 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#246]
Issue :- Home page of mobile view is not correctly given 

Actual Output :- when we are seeing in mobile view of iPhone 12 pro  there are some text which are came out of the input box 

Expected Output :- when we are about see in mobile view it should be  view  correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/eeb770c2-c8dc-4434-8b57-2240d27ecaaf

**Comment by qspaysys2** [comment]
Issue resolved
