### ISSUE TITLE
White Board :- Home Page :: Mobile View >> iPhone 14 pro max 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#248]
Issue :- Home page of mobile view is not correctly given 

Actual Output :- when we are seeing in mobile view of iPhone 14 pro max  there are some text which are came out of the input box 

Expected Output :- when we are about see in mobile view it should be  view  correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/768e4e1d-e51a-423d-82c4-a0051711dbf1

**Comment by qspaysys2** [comment]
Issue resolved
