### ISSUE TITLE
White Board :- Home Page :: Mobile View >>Samsung Galaxy S8+  

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#251]
Issue :- Home page of mobile view is not correctly given

Actual Output :- when we are seeing in mobile view of Samsung Galaxy S8+there are some text which are came out of the input box and also the app  store icon and google play icon compressed 

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/09915d24-ab13-4a2e-8d20-6e943c7dc84a

**Comment by qspaysys2** [comment]
Issue resolved
