### ISSUE TITLE
White Board :- Home Page :: Mobile View >>Samsung Galaxy S20 ultra 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#253]
Issue :- Home page of mobile view is not correctly given

Actual Output :- when we are seeing in mobile view of Samsung Galaxy S20 ultra there are some text which are came out of the input box and also the app store icon and google play icon compressed

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/b24bc1d6-b985-4bd7-b4a9-c0d69a601928

**Comment by qspaysys2** [comment]
Issue resolved
