### ISSUE TITLE
Storex>>Pending actions

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#254]
back Arrow mark will not correct in center position xl size
, lg size
![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/6724291e-ee9c-4377-bd2f-86b65cf274fc)

**Comment by svnashok** [comment]
Above Issued Resolved

**Comment by qspaysys2** [comment]
Above issue resolved

**Comment by svnashok** [comment]
Above Issued Resolved
