### ISSUE TITLE
White Board :- Home Page :: Mobile View >> iPad mini 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#264]
Issue :- Home page of mobile view is not correctly given

Actual Output :- when we are seeing in mobile view of iPad mini there are overflow of text and input  box 

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/f285268d-0514-410c-b82c-925e565bc5d4

**Comment by qspaysys2** [comment]
issue resolved
