### ISSUE TITLE
White Board :- Home Page :: Mobile View >> iPad Air 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#268]
Issue :- Home page of mobile view is not correctly given

Actual Output :- when we are seeing in mobile view of iPad air there are  overflow of text and input  box 

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/add0fcae-2134-479c-9c1f-771c54438106

**Comment by qspaysys2** [comment]
Issue resolved
