### ISSUE TITLE
White Board :- Home Page :: Mobile View >> iPad pro 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#270]
Issue :- Home page of mobile view is not correctly given

Actual Output :- when we are seeing in mobile view of iPad pro  there are overflow of text and input box

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/6dfd1882-289c-4071-8507-f6031b58d743

**Comment by sankarnagarapu** [comment]
Design has chnaged @Dharanimaccha
