### ISSUE TITLE
White Board :- Home Page :: Mobile View >> galaxy z 5 fold 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#276]
Issue :- Home page of mobile view is not accurate

Actual Output :- when we are seeing in mobile view of  galaxy z5 fold   there are overflow of text and input box

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/b33028cb-bae9-4ca8-bd8e-4398b4344078

**Comment by qspaysys2** [comment]
Issue resolved
