### ISSUE TITLE
White Board :- Home Page :: Mobile View >> Asus ZenBook fold 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#278]
Issue :- Home page of mobile view is not accurate

Actual Output :- when we are seeing in mobile view of  Asus ZenBook fold   there are overflow of text and input box

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/4de93997-b914-4577-b328-199edae178f7

**Comment by qspaysys2** [comment]
issue resolved
