### ISSUE TITLE
Storex :; Bank >> Account number >>

### ISSUE THREAD

**Issue by BezawadaMounika** [gak112/ArhaAppsAdminTesting#282]
Issue :- There is an issue in account number.

Actual output :- When we enter the account number more than 16 numbers it is accepted without showing any error .

Expected output :-  If we enter the more than 16 numbers in account number it should not accept & gives the warning .

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170599971/2a57cdbc-1215-41f1-8eb9-cf8062e10a0b)

**Comment by sankarnagarapu** [comment]
Issue Resolved  @BezawadaMounika
