### ISSUE TITLE
Whit Board :- Homepage ;: Mobile view >> Surface pro 7

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#294]
Issue :- Home page of mobile view is not accurate

Actual Output :- when we are seeing in mobile view of surface pro 7  there are overflow of text and input box

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/0dac678e-bdff-4e0e-9f9c-b7904d975045

**Comment by sankarnagarapu** [comment]
Design Changed @Dharanimaccha
