### ISSUE TITLE
Plugins>>App Id

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#295]
while entered the App id it will take only numbers, not special characters , letters, 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/55da9b2c-34ff-4513-9ee1-073a02ddf47b)

**Comment by sankarnagarapu** [comment]
App ID might contain some characters like hyphen @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
