### ISSUE TITLE
Plugins>>cashfree

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#298]
while entered the details , after clicking on submit , isn't working 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/456b25ec-a8d3-43cc-9045-694baed71f23)

**Comment by sankarnagarapu** [comment]
both fields have some minimum length 32 and 54 @svnashok

**Comment by svnashok** [comment]
Above Issued resolved
