### ISSUE TITLE
Whit Board :- Homepage ;: Mobile view >> Surface Duo

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#299]
Issue :- Home page of mobile view is not accurate

Actual Output :- when we are seeing in mobile view of surface Duo  there are overflow of text and input box

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/315aad2d-ad4e-41ec-8e1c-2252554d6021

**Comment by qspaysys2** [comment]
Complete design has been changed
