### ISSUE TITLE
White Board :- Home page ::; Mobile view >> pixel 7

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#300]
Issue :- Home page of mobile view is not accurate

Actual Output :- when we are seeing in mobile view of pixel 7 there are overflow of text and input box

Expected Output :- when we are about see in mobile view it should be view correctly without any extra texts or input boxes

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/27073aae-8b14-4a2e-9d6a-30ea4190dcb2

**Comment by qspaysys2** [comment]
Complete design has been changed
