### ISSUE TITLE
Plugins>>shiprocket

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#306]
Ship rocket API username :- while entered the username , it takes the special characters, numbers , but it includes only letters not numbers 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/2fc13789-3600-4cdc-bafe-5f689311d4a8)

**Comment by sankarnagarapu** [comment]
API username changed to email and validation is complete

**Comment by svnashok** [comment]
Above Issued Resolved
