### ISSUE TITLE
Plugins> Shiprocket

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#310]
Password:- while entered the password , i think it will should maximum of characters is password, 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/72d77a9b-c544-41e3-a4dd-2efd569d12ae)

**Comment by sankarnagarapu** [comment]
Issue Resolved , have set the password max length to 20 chars

**Comment by svnashok** [comment]
Above Issued resolved
