### ISSUE TITLE
Plugins>>Shiprocket

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#312]
Submit Button:- submit button bg is different, can you change the color 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/012e8bb7-3292-4cd2-b0ea-348ca2685d4e)

**Comment by qspaysys2** [comment]
That is inactive status so until you enter all fields it will not come to active mode

**Comment by svnashok** [comment]
Above Issued resolved
