### ISSUE TITLE
White Board :- Home page ::; My categories 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#313]
Issue :-  There is a issue in my categories 

Actual Output :- After  entering  all input boxes of my categories and there is no action on home page

Expected  Output :- When we enter the all the input boxes of it should show green color right mark on the  input box of my categories
![Screenshot 2024-05-24 140116](https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/a404d664-3807-401c-b3f4-d9d13ef5110c)

**Comment by QSPaysys1** [comment]
we changed the design completly., issue resolved
