### ISSUE TITLE
Plugins>>Cashfreee

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#320]
While entered the details , after clicking on submit , it shown the any msg, like saved successfully or Update successfully

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/7e289d71-d726-4e52-ac62-fc520c174a28

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
