### ISSUE TITLE
storex>>plugins>>shiprocket

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#322]
While entered the details , after clicking on submit , it shown the any msg, like saved successfully or Update successfully

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/6d861193-99d6-4a61-8853-b4433dd29348

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued resolved
