### ISSUE TITLE
White Board :- Job<< Add job<< Job Title

### ISSUE THREAD

**Issue by BantuNavya** [gak112/ArhaAppsAdminTesting#326]
Action :- Issues on job Title
Actual Output :- Accpecting numerical numbers on Job title and should not give any warning message or Maximum numbers enter 
Expected Output :- It should accpect only alphabet letters and give warning message 
![Screenshot 2024-05-24 152440](https://github.com/gak112/ArhaAppsAdminTesting/assets/170604838/f4f34b5f-fca2-4f69-b2ad-77b1f8dc3aec)

**Comment by sankarnagarapu** [comment]
A job title can have numbers it @BantuNavya
