### ISSUE TITLE
Issue::>> Item Name::>> Add Product::>> StoreX>:: Testing>>::

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#337]
Result:- There is an issue in entering the Item Name in Add Product of StoreX

Actual Output:- It shows me the issue like "Please Enter minimum 4 characters" before I write a single letter

Expected Output:- It should show the error when the user writes below 4 characters and it shouldn't show a warning before the user enters anything

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/5c9a4a3b-2995-4310-8ca5-dccf42a2719c)

**Comment by sankarnagarapu** [comment]
Issue Resolved @Snehanama19

**Comment by Snehanama19** [comment]
Resolved
