### ISSUE TITLE
Storex>>Sidebar

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#368]
Remove the Login & Signup Buttons, Add teh Logout or Sign out Buttons

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/43f63538-1bc8-461e-a37a-2df5865194ea)

**Comment by sankarnagarapu** [comment]
@qspaysys2

**Comment by svnashok** [comment]
Above Issued Resolved
