### ISSUE TITLE
Storex>>Pending Actions>>Location

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#375]
While entered the correct no, it shown an enter valid shop no , error msg shown an landmark , while type the 7 characters but shown an enter minimum of 4 characters 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/1eb676b6-41d6-4bb6-b304-0c37849e2cf5)

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
