### ISSUE TITLE
Issue:: Error:: StoreX:: Add Product::>>

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#430]
Result:- There is an issue in the Add Product module in Adding Product price and Discount

Actual Output:- When I entered the Product price and Flat Discount which is greater than the Product price it was accepted without showing any error

Expected Output:- It should not allow - digits and show an error

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/d6c5aac6-7e3e-42ec-9d17-0e65d7b6a5d8)

**Comment by sankarnagarapu** [comment]
Issue Resolved @Snehanama19
