### ISSUE TITLE
Storex>>Products>>Product View

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#460]
Price Money Design will be un Proper

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/71f0a55e-d935-4a31-b944-478e31915561)

**Comment by qspaysys2** [comment]
@QSPaysys1 can you pls decrease the decimal value

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
