### ISSUE TITLE
Storex>>Products>>Add Products>>Varients

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#462]
**Varients View**    design will be an unproper

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/26daa3bc-7c27-4072-8c1f-34f403ff78a1)

**Comment by qspaysys2** [comment]
Issue cleared

**Comment by svnashok** [comment]
Above Issued Resolved
