### ISSUE TITLE
FoodX>> Products>> Add product>> Price

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/ArhaAppsAdminTesting#471]
**ISSUE:-**  The price input should have a limit( i.e, 50-60 numbers), May we will get issues if the price has no limt.

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584298/37180bdd-3335-4eac-8785-accc3bc3497a

**Comment by sankarnagarapu** [comment]
Issue Resolved @srinivasmudhiraj3
