### ISSUE TITLE
Issues::>> StoreX:: Testing::>> Add Product::>> Varients::>>

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#475]
Result:- There is an Issue in the Add Product Module Varients

Actual Output:- There is no option to drag for more segments like edit, toggle, and etc...

Expected Output:- It should drag to visit more segments or the varients page should be full-screen 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/65d2b79f-3151-4a3f-8401-6a2260cf022e)

**Comment by QSPaysys1** [comment]
@qspaysys2
