### ISSUE TITLE
Storex>>Products>>Add Products>>Features

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#476]
**Add Features**     while entered the 4  features , shown an 3 feature design will be unproper 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/1977cc85-c63a-40a1-aa8a-ba640967d3b4)

**Comment by qspaysys2** [comment]
Issue cleared

**Comment by svnashok** [comment]
Above Issued Resolved
