### ISSUE TITLE
Storex>.Products>>Add Products>> Features

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#477]
**Features View**   while add the features there is no edit and delete option , if edit or delete the feature , click on add and click the edit and delete , but in my point of view that is too overlap , easy to way the option 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/70c6ee9b-0e6a-40da-ba34-108a9c96ef7c)

**Comment by qspaysys2** [comment]
@QSPaysys1 i have added Edit and delete icons pls do functionality for them

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
