### ISSUE TITLE
StoreX :: Homepage >> Contact us 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#478]
Issue :- There is an issue in contact us 

Actual Issue :- When i click on the contact us input box it is not taking any actions or it is not redirecting to the particular page 

Expected Output :- When i click on the click on the contact us input it should  redirect to the particular page 

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/37657d42-292a-467a-a6ec-e350dff048dc

**Comment by QSPaysys1** [comment]
design is changed
