### ISSUE TITLE
storex---->products---->Special Description

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#483]
Special Description :  9/7 added 
![Screenshot 2024-05-25 124323](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/b41ab58b-b08e-4481-a46b-03f60ee1c20a)

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above Issue Resolved
