### ISSUE TITLE
FoodX>> Templates>> Categories>> Cards design issue

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/ArhaAppsAdminTesting#486]
**ISSUE:-** The cards are not same and they has diffferent dimensions, Please make the uniform dimensions for all cards.

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/143584298/e1e6d3b2-4efd-4977-a569-99347d169634)

**Comment by qspaysys2** [comment]
Actual it is not about size it is for appearing design when seller wants to keep his categories display in his website.
