### ISSUE TITLE
Storex>>Products>>Add Products>> Specifications

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#489]
**Add Specification:-** the  edit & Delete icons will be very big size, please redesign the small size 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/0aa0beae-34f8-489d-b03e-9b077fc4786c)

**Comment by qspaysys2** [comment]
Issue cleard

**Comment by svnashok** [comment]
Above Issued Resolved
