### ISSUE TITLE
 StoreX>>Testing>>Categories >>Issues On Page no-7

### ISSUE THREAD

**Issue by BantuNavya** [gak112/ArhaAppsAdminTesting#493]
Action :- issuse on  Categories page no-7
Actual Output :- when i searching about  Accessories on page no-7  third template having double letters on first word 
![Screenshot 2024-05-25 132427](https://github.com/gak112/ArhaAppsAdminTesting/assets/170604838/f23b0b82-75d6-45d4-a36e-b8ff6131fb73)

**Comment by QSPaysys1** [comment]
issue resolved

**Comment by qspaysys2** [comment]
Issue Resolved
