### ISSUE TITLE
FoodX>>  Home page

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/ArhaAppsAdminTesting#495]
**ISSUE:-** On the left side bar options, when i select a particular option **(Templates)** the selection menu was jumping to the different  menu option **(Orders).**

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584298/bd87e3e9-abcb-44ed-a64d-c0f0a9445f41

**Comment by sankarnagarapu** [comment]
Issue Resolved @srinivasmudhiraj3
