### ISSUE TITLE
FoodX>> Home page>> Offers>> Icons

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/ArhaAppsAdminTesting#498]
**ISSUE:-** Repeated icons for some options mentioned in image.

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/143584298/fc5ded11-8b1f-43f8-8f0e-14b0dcac53e8)

**Comment by sankarnagarapu** [comment]
Issue Resolved @srinivasmudhiraj3
