### ISSUE TITLE
Storex>.Prodcuts>.Add Products> FAQ's

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#506]
**Add Faq:-** while without entered any inputs, after click on submit, it take action successfully, meanwhile its wrong without entered any input how it will use , its not corret

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/9124c1bb-7a0b-428d-bbd9-ebc34f663bd1)

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
