### ISSUE TITLE
Storex>>products>>Add Products>>FAQ's

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#509]
**FAq's View:-**  while submit the FAQ's , when i am entered the incorrect mean while is not any options edit and delete , if again click on add  , then show the edit delete , it is to risky i think 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/bf3d727d-41b8-4975-8264-70cf8e3622c8)

**Comment by qspaysys2** [comment]
Issue resolved

**Comment by svnashok** [comment]
Above Issued Resolved
