### ISSUE TITLE
FoodX>> Products>> Add products>> Upload image issue

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [gak112/ArhaAppsAdminTesting#517]
**ISSUE:-** Product images are not uploading...
**RESULT:-** Showing as Upload failed.

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584298/461d93e3-7603-423a-a01c-69082a22f437

**Comment by sankarnagarapu** [comment]
Upload care Issue @srinivasmudhiraj3
