### ISSUE TITLE
Issue In store X  :: To upload images 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#518]
Issue :- There Is an Issue while uploading a File 
Actual Result  :- The file I uploaded a Jpg file it was indicating uploading failed when I uploaded a file 
Expected Result  :-The above file is jpg It should be uploaded without any error 
![Jpg](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/3496256b-4e16-4c83-978f-092933418585)

**Comment by sankarnagarapu** [comment]
Upload Care Issue @sindhumodugu
