### ISSUE TITLE
ISsue::>> StoreX:: Code Info::>>

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#521]
Issue:- There is an empty bar which is not necessary and it may confuse users before adding code info, instead of that bar we can keep adding code info inputs there

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/1a5e77bb-0a88-4fa1-b435-12e7e3b9abab)

**Comment by QSPaysys1** [comment]
issue resolved
