### ISSUE TITLE
Issue:>> StoreX::>> Code Info::>> Code Information::>>

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#526]
Issue:- There is no option or input for Code Information there are only three options Bar Code, QR Code, and Batch Number. I've entered all these three and tried to submit it, but it wasn't submitting and has a warning like "Please Enter Code Information" where there is no input or option for Code Information

https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/6653205a-d850-45b1-8259-57a176cdd043

**Comment by sankarnagarapu** [comment]
Issue Resolved @Snehanama19
