### ISSUE TITLE
 Issues >>StoreX >> Varients >> 

### ISSUE THREAD

**Issue by BantuNavya** [gak112/ArhaAppsAdminTesting#529]
Action :- issuse on update varients 
Actual Output :-  this card is does'nt scroll and text are starting at image backround 
Expected Output :- Card should be scroll and text will be visiable
![Screenshot 2024-05-25 153157](https://github.com/gak112/ArhaAppsAdminTesting/assets/170604838/7d49845b-4872-41c3-9ad4-858361be65cd)

**Comment by qspaysys2** [comment]
Issue resolved
