### ISSUE TITLE
Issue::>> StoreX::>> Testing::>> Code Info>>::

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#535]
Issue:- There is an Input to add a Serial Number in Code info but it was not visible when the screen was in default zoom, but when the screen was zoomed out the input was visible.

Expected Output:- It should be visible even when the screen is in default zoom

https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/f2537b1f-e327-411a-9d26-cb265294156e

**Comment by QSPaysys1** [comment]
issue resolved
