### ISSUE TITLE
Storex>>Products>>Add Products>>Code Info

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#537]
**Code Info:-**  while enter the code info , it not given a mandatory , mean while i entered the 3 code info, , click on submit, it shows a error msg  

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/cd1327b3-246d-49f2-a95c-8b5c08b73371)

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued resolved
