### ISSUE TITLE
Issue:: StoreX::>> Testing::>> Code Display

### ISSUE THREAD

**Issue by Snehanama19** [gak112/ArhaAppsAdminTesting#540]
Issue:- I've added a bar code, and QR code but they are not displaying with the product 

https://github.com/gak112/ArhaAppsAdminTesting/assets/170600237/7deca391-634e-47e4-8589-c0a993c5b9cb

**Comment by QSPaysys1** [comment]
barcode and qrcode will not display in the product fullview., we use this in the some categories and we stores for some reasons.
