### ISSUE TITLE
Storex>.Products>>Add Product>>Code Info

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#541]
While Entered the bar code , the design overflow outside 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/385d5603-a4c3-44d2-90bd-baf9e4d05b77)

**Comment by qspaysys2** [comment]
@QSPaysys1 @sankarnagarapu

**Comment by svnashok** [comment]
Above Issued resolved
