### ISSUE TITLE
Storex>.Products>.Add Products>>Codeinfo

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#545]
While entered the bar code , meanwhile show the barcode label text, it is risky, if you want see that bar code go to edit option 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/e42dc587-2c24-4003-92b7-331dd95e122f)

**Comment by qspaysys2** [comment]
Issue resolved

**Comment by svnashok** [comment]
Above Issued resolved
