### ISSUE TITLE
products :: Discount type 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#551]
Issue ;- In discount should not take more then 2 digits 
Expected Result  :- In discount option When user takes more than two digits should display as "Do not take more than Two numbers "
Actual Result  :- In discount Option when I take more than two numbers the actual price were in negatives

**Comment by sankarnagarapu** [comment]
In sufficient data @sindhumodugu

**Comment by sindhumodugu** [comment]
![pricing details](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/90d01af9-ba22-41da-afaf-830ffaf8d7fd)
If user add discount percentage to 100 %  should display error message and also do not take more than two numbers
