### ISSUE TITLE
Submit option 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#552]
issue on submit :-The submit option is not working in any form the user get confused and it was not moving to next page

**Comment by sankarnagarapu** [comment]
@sindhumodugu  Insufficient Info like form name or page

**Comment by sindhumodugu** [comment]
Before when I fill all the details click on submit then the submit button working or not I did n't under stand  so I raised the issue 
![submit](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/30d1201b-6857-4a5a-8b1d-b0aad6986986)
