### ISSUE TITLE
Storex>>Products>>Add Products>> Add Brand

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#554]
While uploading a image , if file  will upload failed shows a error msg, but msg will change the color black to red

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/bbbc7fa6-7d8c-4757-b37f-fd1a6cde2e41)

**Comment by qspaysys2** [comment]
it is default color and it was provided by uploadcareunit

**Comment by svnashok** [comment]
Above Issued Resolved
