### ISSUE TITLE
storex--->offers--->coupons

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#555]
coupons--->The code will appear 2 times in the coupon code

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/d7d1529c-700f-4ba5-abb7-e1c6015bbb46)

**Comment by sankarnagarapu** [comment]
Its a glitch @revathigandham28  Issue Resolved

**Comment by revathigandham28** [comment]
Above issue resolved
