### ISSUE TITLE
store X :: pricing details :; Expiry date 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#556]
Issue :- In Expiry date taking more than 4 numbers 
Expected  Result  :- Date should not exceed more than 4 numbers and also should not take all zeros 
Actual Result :-In expiry date section there are taking more than 4 numbers

**Comment by sankarnagarapu** [comment]
In sufficient details @sindhumodugu No screenshot

**Comment by sindhumodugu** [comment]
In expiry date Now year has changed and Error message was now showing
![pricing details](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/c84f365f-8215-4046-bf89-a957e9ccfbfe)
