### ISSUE TITLE
Issue in store X :: while adding variant 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#557]
Issue :- The variants are not in the form 
Expected Result  :- The user can add variants of their products and it should be viewed in product viewing from 
Actual Result :- I am getting this when I try to add Variant 
![variant](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/2ebefe28-95ae-4f19-8256-f442931c98fa)

**Comment by sankarnagarapu** [comment]
Its a technical package problem @sindhumodugu
