### ISSUE TITLE
storex---->coupons

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#558]
coupons:   
If you add the coupons in the store, it will come in the self

 
![Screenshot 2024-05-25 165110](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/8ffc6591-1cca-4174-8900-dcd1941a57b5)

**Comment by sankarnagarapu** [comment]
A seller or user can't create store coupon @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
