### ISSUE TITLE
Storex>>Products>>Add Products>> Product View

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#560]
In Product View, Below the design of Features and Specification will effecting an over attraction , 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/b40051fa-2750-4dd7-8cd6-9f8fd4a7279d)

**Comment by qspaysys2** [comment]
We cannot change the design right now

**Comment by svnashok** [comment]
Above Issued resolved
