### ISSUE TITLE
storex --->offers--->Add Free gift

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#561]
Add Free gift  : submit button not  working

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/4def1868-dcc3-4cf1-bf7e-f1952f396b79)

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
