### ISSUE TITLE
Storex>>Products>>Add Product>>Specifications

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#564]
While adding the two titles of specifications , there is no gap on Y-direction

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/5a62784a-cf2f-4477-836f-acd4790b9bae)

**Comment by qspaysys2** [comment]
Issue resolved

**Comment by svnashok** [comment]
Above Issued resolved
