### ISSUE TITLE
Storex>>Products>>Add Products>>basic Info

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#573]
**Price:-**  while click on currencies in price label , and that i think in that page added on add option it's easy to userfrndly 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/4df5bc85-a9c6-4603-a115-8116dbae836a)

**Comment by qspaysys2** [comment]
Issue Resolved

**Comment by svnashok** [comment]
Above Issued Resolved
