### ISSUE TITLE
storex---->offers---->Deals--->self

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#576]
self---->  (ipad-pro)  lo   no space

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/8f42e2f7-4345-46fc-9c2b-802e6a09baf6)

**Comment by qspaysys2** [comment]
Issue Cleared

**Comment by revathigandham28** [comment]
Above issue resolved
