### ISSUE TITLE
srorex---> offers---> Ordering--->Add section---> Image Border Radius

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#595]
Image Border Radius---->   Image border Radius mandatory  but not giving value but successful 

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/f5ae2691-9445-45b0-a68b-c4fddcf5329e

**Comment by sankarnagarapu** [comment]
Issue Resolved Border  Radius is not mandatory @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
