### ISSUE TITLE
storex---> offers---> Product Recommendations

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#597]
Product Recommendations--->  Delete button not working

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/1e93f97e-b56b-437b-9a8d-5b2ea3ddf179

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
