### ISSUE TITLE
Storex :: Add Product >>Pricing details 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#599]
Issue :- There is an issue in pricing details 

Actual Output :- When i enter the price of the product also i entered discount percentage of the product but the  actual price is coming in decimal  form 

Expected Output :- When we enter the discount percentage of the product it should not give the actual price in decimals 
 
![Screenshot 2024-05-27 140212](https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/fffc67c4-4b70-45df-a8e0-0953bc0b8f14)

**Comment by QSPaysys1** [comment]
issue resolved
