### ISSUE TITLE
storex--->Categories (Services)----> Add Service Category

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#605]
Add Service Category--->Images are not getting deleted and submit button is not working

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/37c0adb8-49b4-44be-aa3d-1ea4bc8b5d74

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
