### ISSUE TITLE
storex--->promotional designs--->Facebook Posts

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#608]
Facebook Posts--->If you click all and whatever, the page numbers are coming but don't come like that

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/f8ec039a-9576-4620-9ea5-45aa0ed865b5

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
