### ISSUE TITLE
Issue in store X :: Add Features 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#609]
Issue :- Add features form when we add more features the description what we write before we submit is not visible 
Expected Result :- All the three options must be visible 
Actual Result :- when I am Adding more features the description is invisible before I submit 
![features](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/d252a35e-cc10-4dd2-9dc8-e77c7138653f)

**Comment by sankarnagarapu** [comment]
Scroll Issue @qspaysys2

**Comment by qspaysys2** [comment]
Issue Cleared
