### ISSUE TITLE
srorex--->CONTACT GROUPS--->Add contacts

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#611]
Add contacts--->If you give special symbols in mobile number, it will be submitted, but it should not be like that.

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/ce7d5142-957c-4ea9-8bcb-910d5efcc54f

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
