### ISSUE TITLE
Issue in store X ::  code info :: Barcode 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#614]
Issue :- The Barcode is moving outside of the designed Field 
Expected Result :- Bar code which we write should not get outside the input text field 
Actual result :- Bar code is coming outside of the designed field 
![bar code](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/20dd8bbe-76c2-415f-8028-652820f7f9f7)

**Comment by qspaysys2** [comment]
we want to limit bar code number.
@QSPaysys1
