### ISSUE TITLE
storex--->Contact Groups---> Contacts

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#615]
Contacts--->The design is not good

![Screenshot 2024-05-27 173700](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/8bb149ba-d135-4a17-b802-1cc10ccc2fae)

**Comment by qspaysys2** [comment]
Issue resolved

**Comment by revathigandham28** [comment]
Above issue resolved
