### ISSUE TITLE
Issue in store X Design  :: Mobile view 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#617]
Issue :- The design position should need to be fixed 
Actual Result :- The design Is moving the card is not visible properly
Expected result :-The design is keep on moving in Mobile view of Samsung Z fold 5fold 5
![window](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/e37cd9af-1289-444c-a751-4c79f8c5cc95)

**Comment by qspaysys2** [comment]
Issue Resolved
