### ISSUE TITLE
Storex>>Offers>>BuyGet

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#631]
**Buy get Card:-** While entered the flat field , taken a lot of numbers , but meanwhile max 10 characters ,seller entered the items, flat, percentage 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/69302205-6139-4c31-9b6a-ae2241e02c12)

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Not resolved 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/cbae69db-7fcc-409b-ab82-2a23a3ee8f8b)

**Comment by svnashok** [comment]
Above Issued Resolved
