### ISSUE TITLE
storex--->offers--->Buy1 Get1

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#632]
Buy1 Get1----> In the item name (-56553435435435) numbers are accepted, but don't come like that.
https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/30701c31-0138-45e7-8603-571969ddfaf9

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
