### ISSUE TITLE
Store X :: Products >> Add Products >> Variants >> Add variants 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#634]
Issue :- There is an  issue  in add variants 

Actual Output :- When I  added variants in the different input boxes of  After that when i want to change another another variant in the respected input box there is no edit option for it 

Expected Output :- There is should be a edit before we submit the variants because if incase we enter wrong variant ...

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/703a9457-73f8-4f6c-90e3-c427fd136218

**Comment by sankarnagarapu** [comment]
Doubt @Dharanimaccha
