### ISSUE TITLE
storex>>Offers>>BUYGET

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#635]
**BUYGET Card:-** In lg size the design is overlap 

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/191910fe-ec2a-4b51-ad87-72ab11c96c76)

**Comment by qspaysys2** [comment]
Total design has been changed

**Comment by svnashok** [comment]
Above Issued Resolved
