### ISSUE TITLE
Store X :: Products  ::  Add Products >> Variants >> Add variants >> Pricing 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#640]
Issue :- There is an issue in  Edit variant 

Actual Output :- when i click on edit variant it is  enabling the input boxes of   price , percentage  and when i change  the Discount  of the price it is not changing in the Final price  and it is showing the price which entered before 

Expected Output :- When we change the Discount the actual  price also should change 

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/7dee8f2b-4c99-47cf-a976-d50c4f4c28d1

**Comment by QSPaysys1** [comment]
issue resolved
