### ISSUE TITLE
storex--->offers--->buy1get1--->store

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#642]
store--->
It takes the value of (-123423434343) in Percentage and  flat . But don't take it like that.

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/6df44f4a-a08d-48a7-9129-5c814b212602

**Comment by sankarnagarapu** [comment]
Issue resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
