### ISSUE TITLE
storex--->offers--->promotional designs---->Facebook Posts

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#645]
Facebook Posts--->Previous button not working properly

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/e4953b13-e497-4437-9dab-d67a20e3f62f

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
