### ISSUE TITLE
Store X :: Products :: Add Products >> Specifications >> Add Specifications

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#646]
Issue :- There is an issue in Add specifications 

Actual Output :- After adding the specification there are two input which is enter keyword and enter value  
In enter value  input box it should accept only  numerical  because value is  indicating for numbers 

Expected Output :-  In the input box clearly mentioned that enter value that means it should accept only  numbers 
or else when we enter it should give a warning 

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/6de11910-f7c8-452a-9388-ad42a9747b0a

**Comment by QSPaysys1** [comment]
![Screenshot 2024-05-30 185812](https://github.com/gak112/ArhaAppsAdminTesting/assets/135007673/3f8706b3-2a07-4bd0-a6bb-0754592a502c)
we can accept both numbers, alhabets, and special chars
