### ISSUE TITLE
Store X :: Products :: Add Products >> Brands 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#648]
Issue :-   There is an issue in Brands 

Actual Output :-  When we upload the image of the brand is not showing on the home page of the brands 

Expected Output :- When we upload image of it it should visible 

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/d0103c43-fd80-42b9-9c6a-e496bf091df5

**Comment by QSPaysys1** [comment]
issue resolved., please check
