### ISSUE TITLE
Storex>>Offers

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#654]
**Offers Main Page:-**  In offers cards , Grid cols 1 given in small size 2 is better to see, looking good

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/e2846373-24a1-48bb-ac74-e324d7974993)

**Comment by qspaysys2** [comment]
Issue Resolved

**Comment by svnashok** [comment]
Above Issued Resolved
