### ISSUE TITLE
Store X :: Products Home Page >> Filters 

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#655]
Issue :- There is an issue in  filters of home page of products 

Actual Result :-  When i open filters  in products it is showing restaurants instead of Textiles or Clothing stores

Expected Output :-  It should show  clothing store 
![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/4b84a0b5-4c76-433f-b8c6-ec83868149df)

**Comment by QSPaysys1** [comment]
issue resolved
