### ISSUE TITLE
Storex>>Offers

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#656]
**Offers Page:-**  check the design of different sizes, in medium size not displayed the sidebar after refreshing , the displayed sidebar

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/b22ccf25-d8b6-4b02-9c78-3a29eb8c21bc

**Comment by qspaysys2** [comment]
No one check in different sizes we only check

**Comment by svnashok** [comment]
Above Issued Resolved
