### ISSUE TITLE
issue In store X :: Deals 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#665]
Issue :- In Deals It was Accepting previous day dates And also Accepting more than 4 letters in year form 
Expected Result :- In deals should not take previous day dates and should show the warning in the form 
Actual Result :- In deals it was accepting before day dates and also in year taking more than 4 numbers

**Comment by sankarnagarapu** [comment]
Issue Resolved @sindhumodugu
