### ISSUE TITLE
foodx---->products(foodx)---> Add products

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#673]
Add products--->Discount (-5.53) will accept given values ​​but should not come like that

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/eef60ed4-13e0-4c12-8452-81185c5cbe47

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
