### ISSUE TITLE
Issue in store X :: Coupons :: Add coupons 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#680]
Issue in title :- In title input text It was accepting Characters 
Issue In percentage :- In percentage text field when I add Negative numbers it was Accepting Negative numbers should get an error like "please enter valid number"
Issue in Minimum Amount :- In minimum amount text field when I add Negative numbers it was Accepting Negative numbers should get an error like "please enter valid Amount " under the text field 
Issue in Up to amount  :-In up to amount text field when I add Negative numbers it was Accepting Negative numbers should get an error like "please enter valid Amount "under the text field

**Comment by sankarnagarapu** [comment]
Issue Resolved @sindhumodugu
