### ISSUE TITLE
foodx---->offers--->Categories (FoodX)----> Add FoodX Category

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#685]
Add FoodX Category--->It's a mistake to say that English name should come in Hindi name

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/854526a1-4d31-4b48-8869-05c59820dcd7

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above Issue Resolved
