### ISSUE TITLE
foodx--->offers--->coupons--->COUPON DETAILS

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#688]
COUPON DETAILS----> In the coupon code, Dottos will take it but don't take it like that

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/35ecdfea-130a-4fea-b9df-286480a1d818)

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
