### ISSUE TITLE
foodx---->offers--->deals---->Add deals

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#689]
Add deals----> The date is not correct
![food 5](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/a367f8e3-6756-416f-ad14-06fe8d2f139d)

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue resolved
