### ISSUE TITLE
Storex>>Products

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#690]
**Products cards Page:-**   While lot of products cards is there, until the go to next page , kindaki velalsivastundhi  so fixed ga petandi

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/33ec8d4b-7428-4ba8-9073-1bffc9b92cfe

**Comment by qspaysys2** [comment]
Issue Resolved

**Comment by svnashok** [comment]
Above Issued Resolved
