### ISSUE TITLE
foodx---->offers---> coupons---> Add coupons

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#691]
Add coupons--->The design will be unproper in different mobile sizes

![food6](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/9146a204-ad59-4669-9139-54df6e58153c)

**Comment by qspaysys2** [comment]
Issue Resolved

**Comment by revathigandham28** [comment]
Above issue resolved
