### ISSUE TITLE
foodx--->offers---->Buy 1 Get 1

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#694]
Buy 1 Get 1--->The Edit  icon size is large
![food7](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/f63e6b27-741f-4d51-be39-3012de8261cd)

**Comment by qspaysys2** [comment]
Design has been changed

**Comment by revathigandham28** [comment]
Above issue resolved
