### ISSUE TITLE
Issue in store X :: Buy 1 get 1 :: view card Design 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#695]
The Edit Icon Is bigger 
![buy 1 get 1](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/ac83595b-d4ee-4d86-b1b0-4b1ecb560128)

**Comment by sankarnagarapu** [comment]
Design has been @sindhumodugu
