### ISSUE TITLE
foodx----> offers--->Buy 1Get1

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#696]
Buy 1Get1--->  
(-23423543545) takes value for buy and items but don't take it like that

![food8](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/b7592c9f-1d45-4b43-a3d7-de560cff650a)

**Comment by sankarnagarapu** [comment]
Issue Resolved @revathigandham28

**Comment by revathigandham28** [comment]
Above issue  resolved
