### ISSUE TITLE
foodx--->offers--->free gift

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#697]
free gift-->submit button is not working

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/0d41138d-d258-4669-aaa1-99ad8406f198

**Comment by QSPaysys1** [comment]
@revathigandham28  issue resolved please check if it clears close the issue

**Comment by revathigandham28** [comment]
Above issue resolved
