### ISSUE TITLE
Storex>>Products>>Add Prodcts>>Variants

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#698]
**Add Variants:-**  The design will be an unproper of delete icon in  above image

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/b348cf0a-4c33-471b-8320-8b4a84c7b3ce)

**Comment by qspaysys2** [comment]
Issue Resolved

**Comment by svnashok** [comment]
Above Issued Resolved
