### ISSUE TITLE
Storex>>Products>>Add Product>>variants>>Add Variants

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#700]
**Edit Variants:-**  While entered the  negative amount of price  , it take successfully,  but it is wrong, it only give the positive values not negative values

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/5df38ef9-668b-4b8c-bb05-052b5210dabf)

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
