### ISSUE TITLE
Storex>>Products>>Add Products>>variants>>Add Variants

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#701]
**Edit Variants:-** When a flat amount is given, it is not deducted from the total price

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/5a26f0c9-5519-42ed-9734-0002b4cdd8e9)

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
