### ISSUE TITLE
Storex>>Products>>Add Products>>Variants>>Add Variants

### ISSUE THREAD

**Issue by svnashok** [gak112/ArhaAppsAdminTesting#702]
**Edit Variants:-**  When a Percentage amount is given, it is not deducted from the total price

![image](https://github.com/gak112/ArhaAppsAdminTesting/assets/154953748/4f309f81-8233-4cbb-9efe-519d8b450605)

**Comment by sankarnagarapu** [comment]
Issue Resolved @svnashok

**Comment by svnashok** [comment]
Above Issued Resolved
