### ISSUE TITLE
storex--->Location

### ISSUE THREAD

**Issue by revathigandham28** [gak112/ArhaAppsAdminTesting#704]
Location---> while enter the dots, in all labels click on proceed it will take successfully , but it's wrong , not shown an valid message 

https://github.com/gak112/ArhaAppsAdminTesting/assets/154953986/41a0056c-0ec1-465b-be89-b957499d5176

**Comment by sankarnagarapu** [comment]
area and landmark may contain doubts @revathigandham28

**Comment by revathigandham28** [comment]
Above issue  Resolved
