### ISSUE TITLE
white bored ::  Issuse on  "doucment page "  >> PROCCED>>

### ISSUE THREAD

**Issue by BantuNavya** [gak112/ArhaAppsAdminTesting#710]
Action :- There is a issue on procced  to next page
Actual Output :- when i click the proceed button it's taking so much time minimum 5mins and still loading 
Expected Output :-  when i click the button gone to next page quickly and when we wrongly enter the cloumn should be intimate or stop the loading and intimate and procced to next within 1 or 2 sec 

https://github.com/gak112/ArhaAppsAdminTesting/assets/170604838/e14bf569-b321-486c-bf7d-d9fff24aaf87

**Comment by sankarnagarapu** [comment]
Document Verification has been changed @BantuNavya
