### ISSUE TITLE
StoreX :: Products >> Add Products >>category

### ISSUE THREAD

**Issue by Dharanimaccha** [gak112/ArhaAppsAdminTesting#728]
Issue :- There is an issue in category 

Actual Output :- After uploading the images the of the product when we enter in the category input box when we select the categories it is not showing the  categories  and also when we search in the search tool  then also it is not showing the  results of the  category 

Expected Output :- When we  search the category in the search bar  it will enable the all the results of the category 

https://github.com/gak112/ArhaAppsAdminTesting/assets/143584640/64138ac0-3610-4f2b-b912-a7a222a77ffa

**Comment by sankarnagarapu** [comment]
categories in product are specifically are selected or added by user @Dharanimaccha
