### ISSUE TITLE
 design Issue In white board design 

### ISSUE THREAD

**Issue by sindhumodugu** [gak112/ArhaAppsAdminTesting#82]
Issue :- There is a Issue in design the delete option is showing outside 
Actual Result :- The delete option  design is out of the field in galaxy Zfold5
Expected result :- The delete option is with in the field in galaxy Zfold5
![samsung](https://github.com/gak112/ArhaAppsAdminTesting/assets/147719689/ce2f5b27-3060-4348-b463-59c323e123f1)

**Comment by sankarnagarapu** [comment]
@qspaysys2
