### ISSUE TITLE
StoreX --> Store Details --> Designation

### ISSUE THREAD

**Issue by vennelakasula** [gak112/ArhaAppsAdminTesting#94]
Test Case Description:
Meaning of Designation is unclear

Enhancement:
Add i "button" next to Designation that describes what it is. 

Expected Output:
When rolled over "i" it should show "Seller Designation (e.g.: Proprietor, Director, Worker)"

**Comment by qspaysys2** [comment]
Issue Resolved

**Comment by vennelakasula** [comment]
Issue resolved as expected
